name: Deploy Multiple Lambda Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda:
          - name: auth-function
            folder: auth-lambda
          - name: books-lambda-function
            folder: Books
          - name: Cart-Check-lambda-function
            folder: CartCheck
          - name: cart-lambda-function
            folder: Cart
          - name: deletebook-lambda-function
            folder: deletebook
          - name: loginLambdaFunction
            folder: loginLambda
          - name: show-cart-lambda-function
            folder: showBooksfromCartTable
          - name: update-user-lambda
            folder: updateUserLambda

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install the zip utility
      - name: Install zip tool
        run: sudo apt-get install -y zip

      # Step 3: Create a ZIP file for the Lambda function
      - name: Create zip file for Lambda function
        run: |
          cd ${{ matrix.lambda.folder }}
          zip -r ../${{ matrix.lambda.folder }}.zip .
          cd ..

      # Step 4: Deploy the Lambda function
      - name: Deploy to AWS Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:eu-north-1:940482452935:function:${{ matrix.lambda.name }}
            --zip-file fileb://${{ matrix.lambda.folder }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
